export const inputs = {
  personal: [
    {
      id: 'firstName',
      name: 'firstName',
      type: 'text',
      autoComplete: 'firstName',
      label: 'First name',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'lastName',
      name: 'lastName',
      type: 'text',
      autoComplete: 'lastName',
      label: 'Last name',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'email',
      name: 'email',
      type: 'email',
      autoComplete: 'email',
      label: 'Email address',
      required: true,
      className: '6',
    },
  ],

  address: [
    {
      id: 'linkedIn',
      name: 'linkedIn',
      type: 'text',
      autoComplete: 'linkedIn',
      label: 'LinkedIn',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '6',
    },
    {
      id: 'country',
      name: 'country',
      type: 'select',
      autoComplete: 'country',
      label: 'Country',
      options: ['Zambia'],
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'address',
      name: 'address',
      type: 'text',
      autoComplete: 'address',
      label: 'Street address',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'city',
      name: 'city',
      type: 'text',
      autoComplete: 'city',
      label: 'City',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'province',
      name: 'province',
      type: 'text',
      autoComplete: 'province',
      label: 'State / Province',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'postalCode',
      name: 'postalCode',
      type: 'text',
      autoComplete: 'postalCode',
      label: 'ZIP / Postal code',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
  ],

  farmer: [
    {
      id: 'firstName',
      name: 'firstName',
      type: 'text',
      autoComplete: 'firstName',
      label: 'First name',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'lastName',
      name: 'lastName',
      type: 'text',
      autoComplete: 'lastName',
      label: 'Last name',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'gender',
      name: 'gender',
      type: 'select',
      autoComplete: 'gender',
      label: 'Sex',
      options: ['Male', 'Female'],
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'village',
      name: 'village',
      type: 'text',
      autoComplete: 'village',
      label: 'Village',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '3',
    },
    {
      id: 'nrc',
      name: 'nrc',
      type: 'text',
      autoComplete: 'nrc',
      label: 'NRC',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'package',
      name: 'package',
      type: 'text',
      autoComplete: 'package',
      label: 'Seed package',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'quantity',
      name: 'quantity',
      type: 'text',
      autoComplete: 'quantity',
      label: 'Seed quantity',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'paid',
      name: 'paid',
      type: 'text',
      autoComplete: 'paid',
      label: 'Paid up in cash',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
    {
      id: 'amount',
      name: 'amount',
      type: 'number',
      autoComplete: 'amount',
      label: 'Loan amount',
      pattern: '^[A-Za-z0-9]{3,16}$',
      required: true,
      className: '2',
    },
  ],
}
